trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployToAKS
  jobs:
  - job: Deploy
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'AKS'
        kubernetesServiceEndpoint: 'AKS'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configurationPath: '/deployment.yaml'
