trigger:
- main # Change this to the branch you want to trigger the pipeline on

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Define your ACR details
  acrName: 'myacrtelemetry2024images'
  dockerImageName: 'nginx:latest' # Image name from Docker Hub
  acrImageName: 'nginx:latest' # Name for the image in ACR

stages:
- stage: PullAndPush
  displayName: 'Pull and Push Docker Image'
  jobs:
  - job: PullAndPush
    displayName: 'Pull and Push'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        # Log in to Azure
        az login --service-principal --username $(servicePrincipalId) --password $(servicePrincipalPassword) --tenant $(tenantId)
        
        # Set the current subscription
        az account set --subscription $(azureSubscription)
        
        # Log in to the Azure Container Registry
        az acr login --name $(acrName)
        
        # Pull the Docker image from Docker Hub
        docker pull $(dockerImageName)
        
        # Tag the image for ACR
        docker tag $(dockerImageName) $(acrName).azurecr.io/$(acrImageName)
        
        # Push the Docker image to ACR
        docker push $(acrName).azurecr.io/$(acrImageName)
      displayName: 'Pull and Push Docker Image'
      env:
        AZURE_CLI: '2.0.0'

    - task: Docker@2
      inputs:
        command: 'logout'
      displayName: 'Docker Logout'
