trigger:
- main # Change this to the branch you want to trigger the pipeline on

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Define your ACR details
  acrName: 'your-acr-name'
  dockerComposeFile: 'docker-compose.yml'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Images'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        # Log in to Azure
        az login --service-principal --username $(servicePrincipalId) --password $(servicePrincipalPassword) --tenant $(tenantId)
        
        # Set the current subscription
        az account set --subscription $(azureSubscription)
        
        # Log in to the Azure Container Registry
        az acr login --name $(acrName)
        
        # Use Docker Compose to build the services defined in the Compose file
        docker-compose -f $(dockerComposeFile) build
        
        # Push the Docker images to ACR
        docker-compose -f $(dockerComposeFile) push
      displayName: 'Build and Push Docker Images'
      env:
        AZURE_CLI: '2.0.0'

    - task: Docker@2
      inputs:
        command: 'logout'
      displayName: 'Docker Logout'
